// Generated by CoffeeScript 1.3.3
(function() {
  var App,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  App = (function() {

    function App() {
      this.keypress = __bind(this.keypress, this);

      var section, _i, _j, _len, _len1, _ref, _ref1;
      this.position = 0;
      this.sections = $('section');
      _ref = this.sections;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        section = _ref[_i];
        $(section).css({
          "background-color": this.randomrgb()
        });
      }
      $(window).keypress(this.keypress);
      _ref1 = this.sections;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        section = _ref1[_j];
        $(section).hide();
      }
    }

    App.prototype.randomrgb = function() {
      return "rgb(" + (this.roundom(180)) + "," + (this.roundom(180)) + "," + (this.roundom(180)) + ")";
    };

    App.prototype.roundom = function(int) {
      return Math.ceil(Math.random() * int);
    };

    App.prototype.keypress = function(event) {
      var section, _i, _len, _ref;
      this.position += 1;
      if (this.position > this.sections.length) {
        this.position = 0;
      }
      _ref = this.sections;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        section = _ref[_i];
        $(section).hide();
      }
      return $(this.sections[this.position]).show();
    };

    return App;

  })();

  $(function() {
    return window.app = new App;
  });

}).call(this);
