// Generated by CoffeeScript 1.3.3
(function() {
  var App;

  App = (function() {

    function App() {
      var section, _i, _len, _ref;
      this.sections = $('section');
      console.log(this.sections);
      _ref = this.sections;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        section = _ref[_i];
        $(section).css({
          "background-color": this.randomrgb()
        });
      }
    }

    App.prototype.randomrgb = function() {
      return "rgb(" + (this.roundom(180)) + "," + (this.roundom(180)) + "," + (this.roundom(180)) + ")";
    };

    App.prototype.roundom = function(int) {
      return Math.ceil(Math.random() * int);
    };

    return App;

  })();

  $(function() {
    return window.app = new App;
  });

}).call(this);
